import type {
    Transaction,
    Account,
    Category,
    Budget,
    Goal,
    BillReminder,
    DashboardStats
} from '../types';

// Default categories
export const defaultCategories: Category[] = [
    { id: '1', user_id: 'mock', name: 'Gaji', icon: 'Briefcase', color: '#10B981', type: 'income', is_default: true },
    { id: '2', user_id: 'mock', name: 'Freelance', icon: 'Laptop', color: '#3B82F6', type: 'income', is_default: true },
    { id: '3', user_id: 'mock', name: 'Investasi', icon: 'TrendingUp', color: '#8B5CF6', type: 'income', is_default: true },
    { id: '4', user_id: 'mock', name: 'Makan & Minum', icon: 'Utensils', color: '#F59E0B', type: 'expense', is_default: true },
    { id: '5', user_id: 'mock', name: 'Transportasi', icon: 'Car', color: '#6366F1', type: 'expense', is_default: true },
    { id: '6', user_id: 'mock', name: 'Belanja', icon: 'ShoppingBag', color: '#EC4899', type: 'expense', is_default: true },
    { id: '7', user_id: 'mock', name: 'Hiburan', icon: 'Film', color: '#14B8A6', type: 'expense', is_default: true },
    { id: '8', user_id: 'mock', name: 'Utilitas', icon: 'Zap', color: '#F97316', type: 'expense', is_default: true },
    { id: '9', user_id: 'mock', name: 'Kesehatan', icon: 'Heart', color: '#EF4444', type: 'expense', is_default: true },
    { id: '10', user_id: 'mock', name: 'Tempat Tinggal', icon: 'Home', color: '#0EA5E9', type: 'expense', is_default: true },
];

// Mock accounts
export const mockAccounts: Account[] = [
    {
        id: '1',
        user_id: 'mock',
        name: 'Rekening Utama',
        type: 'bank',
        balance: 186750000,
        currency: 'IDR',
        color: '#1E40AF',
        icon: 'Building2',
        created_at: '2024-01-01',
        updated_at: '2024-02-01',
    },
    {
        id: '2',
        user_id: 'mock',
        name: 'Tabungan',
        type: 'bank',
        balance: 525000000,
        currency: 'IDR',
        color: '#10B981',
        icon: 'PiggyBank',
        created_at: '2024-01-01',
        updated_at: '2024-02-01',
    },
    {
        id: '3',
        user_id: 'mock',
        name: 'Kartu Kredit',
        type: 'credit_card',
        balance: -18750000,
        currency: 'IDR',
        color: '#EF4444',
        icon: 'CreditCard',
        created_at: '2024-01-01',
        updated_at: '2024-02-01',
    },
    {
        id: '4',
        user_id: 'mock',
        name: 'Dompet Tunai',
        type: 'cash',
        balance: 5250000,
        currency: 'IDR',
        color: '#F59E0B',
        icon: 'Wallet',
        created_at: '2024-01-01',
        updated_at: '2024-02-01',
    },
];

// Mock transactions
export const mockTransactions: Transaction[] = [
    {
        id: '1',
        user_id: 'mock',
        account_id: '1',
        category_id: '1',
        amount: 15000000,
        description: 'Gaji Bulanan',
        date: '2024-02-01',
        type: 'income',
        is_recurring: true,
        created_at: '2024-02-01',
        updated_at: '2024-02-01',
        category: defaultCategories[0],
        account: mockAccounts[0],
    },
    {
        id: '2',
        user_id: 'mock',
        account_id: '1',
        category_id: '4',
        amount: 850000,
        description: 'Belanja Groceries',
        date: '2024-02-01',
        type: 'expense',
        is_recurring: false,
        created_at: '2024-02-01',
        updated_at: '2024-02-01',
        category: defaultCategories[3],
        account: mockAccounts[0],
    },
    {
        id: '3',
        user_id: 'mock',
        account_id: '3',
        category_id: '6',
        amount: 1950000,
        description: 'Tokopedia Purchase',
        date: '2024-01-31',
        type: 'expense',
        is_recurring: false,
        created_at: '2024-01-31',
        updated_at: '2024-01-31',
        category: defaultCategories[5],
        account: mockAccounts[2],
    },
    {
        id: '4',
        user_id: 'mock',
        account_id: '1',
        category_id: '5',
        amount: 450000,
        description: 'Gojek Rides',
        date: '2024-01-30',
        type: 'expense',
        is_recurring: false,
        created_at: '2024-01-30',
        updated_at: '2024-01-30',
        category: defaultCategories[4],
        account: mockAccounts[0],
    },
    {
        id: '5',
        user_id: 'mock',
        account_id: '1',
        category_id: '7',
        amount: 159000,
        description: 'Netflix Subscription',
        date: '2024-01-28',
        type: 'expense',
        is_recurring: true,
        created_at: '2024-01-28',
        updated_at: '2024-01-28',
        category: defaultCategories[6],
        account: mockAccounts[0],
    },
    {
        id: '6',
        user_id: 'mock',
        account_id: '1',
        category_id: '2',
        amount: 8000000,
        description: 'Freelance Project',
        date: '2024-01-25',
        type: 'income',
        is_recurring: false,
        created_at: '2024-01-25',
        updated_at: '2024-01-25',
        category: defaultCategories[1],
        account: mockAccounts[0],
    },
    {
        id: '7',
        user_id: 'mock',
        account_id: '1',
        category_id: '8',
        amount: 1450000,
        description: 'Tagihan Listrik',
        date: '2024-01-22',
        type: 'expense',
        is_recurring: true,
        created_at: '2024-01-22',
        updated_at: '2024-01-22',
        category: defaultCategories[7],
        account: mockAccounts[0],
    },
    {
        id: '8',
        user_id: 'mock',
        account_id: '1',
        category_id: '4',
        amount: 625000,
        description: 'Makan Malam Restoran',
        date: '2024-01-20',
        type: 'expense',
        is_recurring: false,
        created_at: '2024-01-20',
        updated_at: '2024-01-20',
        category: defaultCategories[3],
        account: mockAccounts[0],
    },
];

// Mock budgets
export const mockBudgets: Budget[] = [
    {
        id: '1',
        user_id: 'mock',
        category_id: '4',
        amount: 6000000,
        spent: 4200000,
        period: 'monthly',
        start_date: '2024-02-01',
        created_at: '2024-02-01',
        category: defaultCategories[3],
    },
    {
        id: '2',
        user_id: 'mock',
        category_id: '5',
        amount: 2000000,
        spent: 1450000,
        period: 'monthly',
        start_date: '2024-02-01',
        created_at: '2024-02-01',
        category: defaultCategories[4],
    },
    {
        id: '3',
        user_id: 'mock',
        category_id: '6',
        amount: 4000000,
        spent: 3800000,
        period: 'monthly',
        start_date: '2024-02-01',
        created_at: '2024-02-01',
        category: defaultCategories[5],
    },
    {
        id: '4',
        user_id: 'mock',
        category_id: '7',
        amount: 1500000,
        spent: 750000,
        period: 'monthly',
        start_date: '2024-02-01',
        created_at: '2024-02-01',
        category: defaultCategories[6],
    },
];

// Mock goals
export const mockGoals: Goal[] = [
    {
        id: '1',
        user_id: 'mock',
        name: 'Dana Darurat',
        description: 'Bangun dana darurat 6 bulan',
        target_amount: 100000000,
        current_amount: 60000000,
        deadline: '2024-12-31',
        category: 'emergency_fund',
        color: '#10B981',
        icon: 'Shield',
        created_at: '2024-01-01',
        updated_at: '2024-02-01',
    },
    {
        id: '2',
        user_id: 'mock',
        name: 'Liburan Jepang',
        description: 'Trip ke Tokyo dan Kyoto',
        target_amount: 75000000,
        current_amount: 42000000,
        deadline: '2024-08-01',
        category: 'vacation',
        color: '#F59E0B',
        icon: 'Plane',
        created_at: '2024-01-01',
        updated_at: '2024-02-01',
    },
    {
        id: '3',
        user_id: 'mock',
        name: 'DP Mobil Baru',
        description: 'Tabung untuk DP 20%',
        target_amount: 120000000,
        current_amount: 48000000,
        deadline: '2025-06-01',
        category: 'car',
        color: '#6366F1',
        icon: 'Car',
        created_at: '2024-01-01',
        updated_at: '2024-02-01',
    },
];

// Mock bill reminders
export const mockBillReminders: BillReminder[] = [
    {
        id: '1',
        user_id: 'mock',
        name: 'Sewa/Cicilan Rumah',
        amount: 5000000,
        due_date: '2024-02-05',
        frequency: 'monthly',
        category_id: '10',
        is_paid: false,
        auto_pay: true,
        created_at: '2024-01-01',
    },
    {
        id: '2',
        user_id: 'mock',
        name: 'Internet',
        amount: 599000,
        due_date: '2024-02-10',
        frequency: 'monthly',
        category_id: '8',
        is_paid: false,
        auto_pay: true,
        created_at: '2024-01-01',
    },
    {
        id: '3',
        user_id: 'mock',
        name: 'Pulsa & Paket Data',
        amount: 150000,
        due_date: '2024-02-15',
        frequency: 'monthly',
        category_id: '8',
        is_paid: false,
        auto_pay: false,
        created_at: '2024-01-01',
    },
];

// Dashboard stats (computed from mock data)
export const mockDashboardStats: DashboardStats = {
    totalBalance: mockAccounts.reduce((sum, acc) => sum + acc.balance, 0),
    monthlyIncome: 23000000,
    monthlyExpenses: 8500000,
    savingsRate: ((23000000 - 8500000) / 23000000) * 100,
    recentTransactions: mockTransactions.slice(0, 5),
    upcomingBills: mockBillReminders,
    budgetProgress: mockBudgets,
    goalProgress: mockGoals,
};

// Monthly spending data for charts
export const monthlySpendingData = [
    { month: 'Sep', income: 20000000, expenses: 12000000 },
    { month: 'Oct', income: 21500000, expenses: 11500000 },
    { month: 'Nov', income: 20500000, expenses: 13000000 },
    { month: 'Dec', income: 25000000, expenses: 15000000 },
    { month: 'Jan', income: 23000000, expenses: 10500000 },
    { month: 'Feb', income: 23000000, expenses: 8500000 },
];

// Category spending breakdown
export const categorySpendingData = [
    { name: 'Makan & Minum', value: 4200000, color: '#F59E0B' },
    { name: 'Transportasi', value: 1450000, color: '#6366F1' },
    { name: 'Belanja', value: 3800000, color: '#EC4899' },
    { name: 'Hiburan', value: 750000, color: '#14B8A6' },
    { name: 'Utilitas', value: 2250000, color: '#F97316' },
    { name: 'Kesehatan', value: 1500000, color: '#EF4444' },
    { name: 'Tempat Tinggal', value: 5000000, color: '#0EA5E9' },
];
